<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-19 at 13:44:00.
 */
 include 'test1.php';
 
class test1Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var test1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new test1;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers test1::setFuga
     * @todo   Implement testSetFuga().
     */
    public function testSetFuga()
    {
        // Remove the following lines when you implement this test.
        /*$this->markTestIncomplete(
          'This test has not been implemented yet.'
        );*/
        $this->setUp();
        $this->object->setFuga("testFuga");
        $this->assertEquals($this->object->fuga, "testFuga");
    }

    /**
     * @covers test1::setFugafuga
     * @todo   Implement testSetFugafuga().
     */
    public function testSetFugafuga()
    {
        $this->testSetFuga();
        $this->object->setFugaFuga("testFugaFuga");
        $this->assertEquals($this->object->fugafuga, "testFugaFuga");
    }

    /**
     * @covers test1::fugafugafuga
     * @todo   Implement testFugafugafuga().
     */
    public function testFugafugafuga()
    {
        $this->testSetFugaFuga();
        $this->assertEquals($this->object->fugafugafuga(), "testFuga testFugaFuga");
    }
}
