<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-19 at 13:44:00.
 */
 include '../application/models/data_model.php';
 
class testData_model extends PHPUnit_Framework_TestCase
{
    protected $object;

    protected function setUp()
    {
        $this->object = new Data_model;
    }
	
    protected function tearDown()
    {
    }

    /**
     * @covers test1::setFuga
     * @todo   Implement testSetFuga().
     */
    public function testSetFuga()
    {
        // Remove the following lines when you implement this test.
        /*$this->markTestIncomplete(
          'This test has not been implemented yet.'
        );*/
        $this->setUp();
        $this->object->setFuga("testFuga");
        $this->assertEquals($this->object->fuga, "testFuga");
    }
}
